language: python

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

services:
  - docker
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - flake8 app.py
  - coverage run --source app.py -m py.test

after_success:
  - coveralls

notifications:
  email: false