sudo: false

language: python

python:
  - "3.6"
#  - "3.7" # Currently broken on Travis-CI

branches:
  only:
    - master

services:
  - docker
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - flake8 app.py
  - coverage run --include app.py -m py.test
  - docker build -t dwilliams-kenzan/catternauts-api:latest .

after_success:
  - coveralls

notifications:
  email: false
